### ISSUE TITLE
Gbatemp

### ISSUE THREAD

**Issue by pauljames80** [turtle-insect/UnicornOverlord#1]
There stuff posted on gbatemp if you haven't seen it yet https://gbatemp.net/threads/unicorn-overlord-save-editing.650584/

**Comment by turtle-insect** [comment]
https://gbatemp.net/threads/unicorn-overlord-1-01-tid-010069401adb8000-bid-e2876f945a831d78.650127/

**Comment by pauljames80** [comment]
https://docs.google.com/spreadsheets/d/1UXe4nEloKlv14P4H4cOKeJc8R2P1fZW_HaLAuQG96BQ/edit?usp=drivesdk

**Comment by turtle-insect** [comment]
great work

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/UnicornOverlord
