### ISSUE TITLE
[Feature Request] Hope to have the following convenient functions

### ISSUE THREAD

**Issue by duanyunlun** [turtle-insect/UnicornOverlord#3]
It is an amazing save editor! Thank you for the hard work! I hope that future versions can add the following convenient functions.
**Menu Option**
1, Multi-language options (I've translated the chinese version of the txt files in 'info' folder).
**Character Area:**
1, Show each Character's name on the left ListBox. 
**Item & Equipment Area:**
1, Multiple selection;
2, Multiple Change the selected Items & equipments at a time;
3, Show item's property and skill.

Thx for the great job again!

**Comment by pauljames80** [comment]
There are name ids in spreadsheet on gbatemp mostly if its a recruited characters. You only really need to add ids from 1 to 200 and 626 to 700. I don't think its important to name hired characters as your only really interested in their class. The only real difference between hired and recruited is the name address if recruits address is FF FF FF FF then game uses hired name address. But if you edit a hired characters recruit address game ignores hired name Id and uses recruits name. So you can just turn hired into recruit.

**Comment by turtle-insect** [comment]
support multi language
https://github.com/turtle-insect/UnicornOverlord/commit/7dc791046208bc1ab249fbdd5d9bce1df907f56d

**Comment by turtle-insect** [comment]
character's name
https://github.com/turtle-insect/UnicornOverlord/commit/cc70653faceb6bea637255521421c34d294cd084
